#
# Module manifest for module 'PSGraphViz'
#
# Generated by: Kevin Marquette
#
# Generated on: 1/11/2017
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'PSGraph.psm1'

    # Version number of this module.
    ModuleVersion     = '3.1.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID              = '03a82298-c9af-48b5-b607-72988687759b'

    # Author of this module
    Author            = 'Kevin Marquette'

    # Company or vendor of this module
    # CompanyName = 'Unknown'

    # Copyright statement for this module
    Copyright         = '(c) 2018 Kevin Marquette. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Builds graphs using GraphViz'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('Cells','Edge','Entity','Export-PSGraph','Graph','Inline','Install-GraphViz','New-EdgeAttributeSet','New-NodeAttributeSet','Node','Rank','Record','Row','Set-NodeFormatScript','Show-PSGraph','SubGraph')

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @(
        'digraph', 'NodeAttributes', 'EdgeAttributes',
        'jpgGraph', 'pngGraph', 'gifGraph', 'imapGraph', 'cmapxGraph',
        'jp2Graph', 'jsonGraph', 'pdfGraph', 'plainGraph', 'dotGraph', 'svgGraph'
    )

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('graph', 'visualization', 'DSL')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/themodulecollective/PSGraph/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/themodulecollective/PSGraph'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = @'
3.1.0 20260829
* Format-Value: fixed HTML-like label detection so any valid GraphViz
  HTML-like label round-trips, not just ones starting with <table (#100)
* Record: added -TableAttributes to control the outer <TABLE> element,
  e.g. hiding borders between every row in one call (#81)
* Row: added -Separator to emit a dedicated thin divider row (#81)
* Cells: new command converting pipeline objects into HTML table rows
  for use inside a Record
* Export-PSGraph: added format-specific aliases (pngGraph, svgGraph,
  dotGraph, etc., one per -OutputFormat value)
* Restored Windows PowerShell 5.1 support (CompatiblePSEditions is now
  Desktop and Core; PowerShellVersion lowered back to 5.1)

3.0.0 20260829
See CHANGELOG.md for the full list of fixes and features in this release.
* Export-PSGraph: fixed -ShowGraph on paths with spaces, fixed BOM/
  non-ASCII output breaking dot on some platforms, added cross-platform
  `dot` auto-detection via Get-Command, added -PassThru for in-memory
  (e.g. SVG) output
* Graph: fixed compound=$false being silently overridden
* Rank: added -RankType (min/source/max/sink, not just same)
* Row: added -Attributes for row-level HTML attributes; fixed GUID-style
  port name handling
* Install-GraphViz: added -Scope CurrentUser for non-admin installs,
  with a nuget.org fallback when Chocolatey can't be registered
* New-NodeAttributeSet / New-EdgeAttributeSet: new commands for building
  case-correct GraphViz attribute hashtables with tab completion
* Tests migrated to Pester 5; CI migrated to GitHub Actions across
  Windows/Linux/macOS

2.1.16 20180217
* add Record command
* add Row command
* add Entity command
* add Show-PSGraph command
* add key name case correction
* throws error when there are graphviz parse errors

1.2.0 20171022
* #53 add support for edges to and from a subgraph
* #55 subgraph name is now optional
* 56 remove extra blank lines in graph output

1.1.4 20171021
* #51 Updated build script

1.1.3 20171021
* #40 fixed positional attributes with Edge

1.1.1 20171021
* Added -ranked switch to node to auto create a rank

1.1.0 20171021
* Made graph name optional
* Added legacy layout engine names to export-psgraph

'@

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
